# VowelClassCollection { #new_fave.measurements.vowel_measurement.VowelClassCollection }

`measurements.vowel_measurement.VowelClassCollection(self, track_list)`

A class for an entire vowel system. It is a subclass
of `defaultdict`, so it can be keyed by vowel class 
label

## Parameters

| Name         | Type                  | Description                              | Default    |
|--------------|-----------------------|------------------------------------------|------------|
| `track_list` | list\[CandidateTracks | A list of `fasttrackpy.CandidateTrack`s. | _required_ |

## Attributes

| Name                    | Type                                                                                             | Description                                                                                  |
|-------------------------|--------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------|
| maximum_formant_cov     | [np](`numpy`).[array](`numpy.array`)                                                             | The covariance matrix for the winners maximum formant across the entire vowel system         |
| maximum_formant_means   | [np](`numpy`).[array](`numpy.array`)                                                             | The mean maximum formant for the winners across the entire vowel system                      |
| max_formant_icov        | [np](`numpy`).[array](`numpy.array`)                                                             | The inverse covariance matrix for the winners maximum formant across the entire vowel system |
| params_covs             | [np](`numpy`).[array](`numpy.array`)                                                             | The covariance matrix for the winners' DCT parameters.                                       |
| params_icov             | [np](`numpy`).[array](`numpy.array`)                                                             | The inverse covariance matrix for the winners'  DCT parameters.                              |
| params_means            | [np](`numpy`).[array](`numpy.array`)                                                             | An `np.array` for the winners' DCT parameters in the entire vowel system.                    |
| vowel_measurements      | [list](`list`)\[[VowelMeasurement](`new_fave.measurements.vowel_measurement.VowelMeasurement`)\] | A list of all vowel measurements in the  vowel system                                        |
| winner_formants         | [np](`numpy`).[array](`numpy.array`)                                                             | An `np.array` for the formants  for the winners in the entire vowel system.                  |
| winner_params           | [np](`numpy`).[array](`numpy.array`)                                                             | An `np.array` of DCT parameters for the winners in entire vowel system.                      |
| winners                 | [list](`list`)\[[fasttrackpy](`fasttrackpy`).[OneTrack](`fasttrackpy.OneTrack`)\]                | The winning `fasttrackpy.OneTrack` for  the entire vowel system                              |
| winners_maximum_formant | [np](`numpy`).[array](`numpy.array`)                                                             | An `np.array` of the maximum formants for the winners in the entire vowel system             |

## Methods

| Name | Description |
| --- | --- |
| [to_param_df](#new_fave.measurements.vowel_measurement.VowelClassCollection.to_param_df) | Return DataFrame of formant DCT parameters. |
| [to_point_df](#new_fave.measurements.vowel_measurement.VowelClassCollection.to_point_df) | Return a DataFrame of point measurements |
| [to_tracks_df](#new_fave.measurements.vowel_measurement.VowelClassCollection.to_tracks_df) | Return a DataFrame of the formant tracks |

### to_param_df { #new_fave.measurements.vowel_measurement.VowelClassCollection.to_param_df }

`measurements.vowel_measurement.VowelClassCollection.to_param_df(output='log_param')`

Return DataFrame of formant DCT parameters.

#### Returns

| Type                                           | Description                           |
|------------------------------------------------|---------------------------------------|
| [pl](`polars`).[DataFrame](`polars.DataFrame`) | A DataFrame of formant DCT parameters |

### to_point_df { #new_fave.measurements.vowel_measurement.VowelClassCollection.to_point_df }

`measurements.vowel_measurement.VowelClassCollection.to_point_df()`

Return a DataFrame of point measurements

#### Returns

| Type                                           | Description                          |
|------------------------------------------------|--------------------------------------|
| [pl](`polars`).[DataFrame](`polars.DataFrame`) | A DataFrame of vowel point measures. |

### to_tracks_df { #new_fave.measurements.vowel_measurement.VowelClassCollection.to_tracks_df }

`measurements.vowel_measurement.VowelClassCollection.to_tracks_df()`

Return a DataFrame of the formant tracks

#### Returns

| Type                                           | Description                          |
|------------------------------------------------|--------------------------------------|
| [pl](`polars`).[DataFrame](`polars.DataFrame`) | A dataframe with formant track data. |