name: Dev Tag

on:        
  pull_request:
    types:
      - closed
    branches:
      - 'dev'

jobs:
  dev-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Bump Version
        run: echo "PKG_VERSION=$(poetry version prerelease | awk '{print $6}')" >> $GITHUB_ENV
      - name: Test
        run: echo ${{ env.PKG_VERSION }}
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          ref: ${{ env.PKG_VERSION }}
      - name: Push Dev Version
        run: |
          git config --global user.name "Dev Tagger"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.PKG_VERSION }}"
          git push